# Generated by Django 4.1.3 on 2022-12-08 22:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ejemplo', '0002_datosfamilia'),
    ]

    operations = [
        migrations.DeleteModel(
            name='DatosFamilia',
        ),
    ]
