# Generated by Django 4.1.3 on 2022-12-08 23:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ejemplo', '0003_delete_datosfamilia'),
    ]

    operations = [
        migrations.CreateModel(
            name='MVPFamiliares',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('direccion', models.CharField(max_length=200)),
                ('localidad', models.CharField(max_length=100)),
                ('trabajo', models.CharField(max_length=100)),
            ],
        ),
    ]
