# Generated by Django 4.1.3 on 2022-12-27 05:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('turismo_arg', '0003_post_imagen_alter_avatar_imagen'),
    ]

    operations = [
        migrations.CreateModel(
            name='Mensaje',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254)),
                ('nombre', models.CharField(max_length=100)),
                ('texto', models.TextField(max_length=100)),
                ('enviado_el', models.DateField(auto_now_add=True)),
            ],
        ),
        migrations.AlterField(
            model_name='avatar',
            name='imagen',
            field=models.ImageField(blank=True, null='True', upload_to='avatares'),
        ),
    ]
